// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUeqHYtqoRAj0KRs6cIRCtu3MQH4hjvpQ',
    appId: '1:696514852788:web:86c33bc704a0161436a4e1',
    messagingSenderId: '696514852788',
    projectId: 'foodgo-a8908',
    authDomain: 'foodgo-a8908.firebaseapp.com',
    storageBucket: 'foodgo-a8908.firebasestorage.app',
    measurementId: 'G-BX0BN0CYJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2n9dmn3hZVCloOBD3sAsJRgkldbJ4rsU',
    appId: '1:696514852788:android:0ff82db9294efac636a4e1',
    messagingSenderId: '696514852788',
    projectId: 'foodgo-a8908',
    storageBucket: 'foodgo-a8908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6p6zTioFZgkthDON5liVB7ICplxPukX0',
    appId: '1:696514852788:ios:082ebc4936e52e2436a4e1',
    messagingSenderId: '696514852788',
    projectId: 'foodgo-a8908',
    storageBucket: 'foodgo-a8908.firebasestorage.app',
    iosBundleId: 'com.example.foodGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6p6zTioFZgkthDON5liVB7ICplxPukX0',
    appId: '1:696514852788:ios:082ebc4936e52e2436a4e1',
    messagingSenderId: '696514852788',
    projectId: 'foodgo-a8908',
    storageBucket: 'foodgo-a8908.firebasestorage.app',
    iosBundleId: 'com.example.foodGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUeqHYtqoRAj0KRs6cIRCtu3MQH4hjvpQ',
    appId: '1:696514852788:web:8acd17b1fcf4e02736a4e1',
    messagingSenderId: '696514852788',
    projectId: 'foodgo-a8908',
    authDomain: 'foodgo-a8908.firebaseapp.com',
    storageBucket: 'foodgo-a8908.firebasestorage.app',
    measurementId: 'G-C1KFTQ3TED',
  );
}
